### ISSUE TITLE
EasyShell not compatible with new Eclipse Neon

### ISSUE THREAD

**Issue by belpk** [anb0s/EasyShell#45]
Eclipse Neon is released yesterday.
But EasyShell can't installed nor used anymore.

>   Missing requirement: Easy Shell Feature 1.4.2 (com.tetrade.eclipse.plugins.easyshell.feature.feature.group 1.4.2) requires 'org.eclipse.core.runtime.compatibility 0.0.0' but it could not be found

Seems the latest EasyShell release dates from 2014, so I guess this project is dead? So as it doesn't work anymore, I guess that's the end of it?
A shame. Well, time to switch to alternative similar plugins instead...

**Comment by anb0s** [comment]
Thanks for the report, but the words "A shame. Well, time to switch to alternative similar plugins instead" etc. are no help for me to give more of my spare time for EasyShell development...
Other plugins that i like you can try instead:
- https://marketplace.eclipse.org/content/startexplorer
- https://marketplace.eclipse.org/content/open-explorer
- https://marketplace.eclipse.org/content/path-tools

Anyway i have a working version for Neon and wanted to release it together with Neon, but it will be released in the same week later, see milestone v1.5

**Comment by anb0s** [comment]
related to #30

**Comment by anb0s** [comment]
related to https://sourceforge.net/p/pluginbox/bugs/26/

**Comment by fabrejc** [comment]
Thanks for your plugin, it is really very useful, I use it for years and it helps me a lot!
Thanks for the time you give to maintain it!

**Comment by electrotype** [comment]
Same here: thank you very much for this plugin! I use it every day.

**Comment by p91paul** [comment]
Is there an early binary for the 1.5/2.0 release, or an easy way to build one from source?

**Comment by anb0s** [comment]
I've an internal alpha version of 1.5 stream that is ONLY for playing with some new features i want to add. BUT this version is not compatible to 1.4.x nor to new 2.0 stream. So if you have own presets, they will not be usable, because if new property-format. It also has possibility to have 3 EasyShell menu instances --> fist enable one instance in preferences:

![image](https://cloud.githubusercontent.com/assets/95811/16563079/62949800-4200-11e6-815c-57e2fdf364c3.png)

All three configured intances of EasyShell menus (some entries are duplicates) looks like this:

![image](https://cloud.githubusercontent.com/assets/95811/16563062/47466696-4200-11e6-9351-1e20a2a77b72.png)

I will release new v2.0 instead of v1.5 officially, because the interface is clear and simple, but it supports dynamic menus, you can select the tools you want instead of having 4 predefined, see 
issue #9 and #14 etc.

So v1.5 will have no future ;) but if you want to use for Neon until v2.0, testing update site: http://anb0s.github.io/EasyShell/testing

v2.0 pre-release will be added during this week...

Thanks!

**Comment by electrotype** [comment]
Hi anb0s, 

I'm not sure in which issue I should suggest this but since you posted those images here... Wouldn't it be nice if one could simply add and remove _custom entries_, with custom names? You could keep the suggested "templates" but also allow to add/remove any entry?

I suck at photoshop, but something like this:

![](http://i.imgur.com/oERxjM3.png)

**Comment by anb0s** [comment]
Thanks! The version v2.0 that i'm preparing has something similar, one can add, remove, enable/disable predefined and own commands / presets:

![image](https://cloud.githubusercontent.com/assets/95811/16569524/c883ebd4-4237-11e6-8d71-d5c40cb5691b.png)

I hope it will solve the most requests in this direction, like issue #9 and #14 :)

**Comment by electrotype** [comment]
Nice!!!

**Comment by anb0s** [comment]
done at branch v2_0

**Comment by electrotype** [comment]
I'm currently testing it in Neon and it works well!

1. There is a NPE if you create an item and then change its "type" to "Other" (and you click "OK")
2. Would be nice to list the new names to use as arguments since "{1}", "{2}", etc. don't work anymore.
3. If it can help someone, I primarily use EasyShell to pop Windows Context Menu. To do that, I now use this as my command in Neon: 

C:\path\to\WinContextMenu_x64.exe "${easyshell:resource_loc}

"WinContextMenu_x86.exe" and "WinContextMenu_x64.exe" are avaialble there:
https://github.com/vkalviss/WinContextMenu/tree/master/bin

Thanks for that 2.0 version!!

**Comment by electrotype** [comment]
- Another small bug: when you click the "Edit" button for an item, its "type" is always reset to "Open".

**Comment by anb0s** [comment]
Thank You for the alpha test! So you have builded it by yourself :)

I have more patches to apply and adapt to new codebase from my private work done in 2015, so may be some commits have issues. I will commit it during the week, so please wait for the last one that should be stable and have all UI elements available :) I will put the beta release to testing site --> i have to do it step by step...

> 1. There is a NPE if you create an item and then change its "type" to "Other" (and you click "OK")
Yes, the new icon path was wrong here --> fixed with next commit

> Would be nice to list the new names to use as arguments since "{1}", "{2}", etc. don't work anymore.
Yes, comes with next commit together with other elements of prefernec page (string tokenizer, variable assist etc.)

> If it can help someone, I primarily use EasyShell to pop Windows Context Menu. To do that, I now > use this as my command in Neon:
> C:\path\to\WinContextMenu_x64.exe "${easyshell:resource_loc}
Cool, i will try it too!

> Another small bug: when you click the "Edit" button for an item, its "type" is always reset to "Open".
OK, will check it.

Thanks electrotype!

**Comment by anb0s** [comment]
I have added this v2.0 issues to #50 and will track it there.

**Comment by anb0s** [comment]
fixed with 6aac78165ce49ddec00282e3a3ed97b23b3ba5f5

**Comment by anb0s** [comment]
v2.0.0 beta 2 build available at site: http://anb0s.github.io/EasyShell/testing
version: EasyShell 2.0.0.v20160719-1230
see issue #54 for found bugs and general discussion

@all users: Thanks again for your support :)
